version: '3'

services:
  web:
    container_name: lm-web
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ../src:/src
      - ../site.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - php
    expose:
      - 80
    labels:
      - "traefik.port=80"
      - 'traefik.backend=traefik'
      - 'traefik.enable=true'
      - "traefik.frontend.rule=Host:api.marconi.demo.vivedo.me"

  php:
    container_name: lm-php
    build:
      context: ./php
    volumes:
      - ../src:/src
    links:
      - mariadb:database
    labels:
      - traefik.enable=false

  mariadb:
    container_name: lm-mdb
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: labmanager
      MYSQL_DATABASE: labmanager
      MYSQL_USER: labmanager
      MYSQL_PASSWORD: labmanager
    volumes:
      - database-data:/var/lib/mysql
      - ../sql:/sql
    labels:
      - traefik.enable=false
  
  traefik:
    image: traefik:alpine
    restart: always
    command: --api
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../traefik.toml:/traefik.toml
      - ../acme.json:/acme.json
    container_name: traefik
    expose:
      - 8080
    labels:
      - "traefik.port=8080"
      - 'traefik.backend=traefik'
      - 'traefik.enable=true'
      - "traefik.frontend.rule=Host:traefik.marconi.demo.vivedo.me"
    ports:
     - "9090:8080"

volumes:
  database-data:

networks:
  proxy:
    external: true