version: '3'

services:
  phpMyAdmin:
    container_name: lm-pma
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: database
      PMA_USER: labmanager
      PMA_PASSWORD: labmanager
    links:
      - mariadb:database
    expose:
      - 80
    labels:
      - "traefik.port=80"
      - 'traefik.backend=phpmyadmin'
      - 'traefik.enable=true'
      - "traefik.frontend.rule=Host:phpmyadmin.marconi.demo.vivedo.me"
    networks:
      - proxy
