version: '3'

services:
  phpMyAdmin:
    container_name: lm-pma
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: database
      PMA_USER: labmanager
      PMA_PASSWORD: labmanager
    links:
      - mariadb:database
    ports:
      - 8000:80
    labels:
      - traefik.backend=blog
      - traefik.frontend.rule=Host:api.marconi.demo.vivedo.me
      - traefik.docker.network=proxy
      - traefik.port=80
    networks:
      - proxy
